name: MandoMCRemade
version: '${project.version}'
main: net.mandomc.mandomcremade.MandoMCRemade
api-version: '1.20'
load: STARTUP
authors: [ AstuteFlamez ]
description: A core plugin for the minecraft server MandoMC.
softdepend: [MythicMobs,WorldGuard]
commands:
  warp:
    aliases: warps