name: MandoMCRemade
version: '${project.version}'
main: net.mandomc.mandomcremade.MandoMCRemade
api-version: '1.21'
authors: [ AstuteFlamez ]
description: A core plugin for the minecraft server MandoMC.
softdepend: [MythicMobs,WorldGuard,ProtocolLib,Citizens]
commands:
  mmc:
  koth: