name: MandoMCRemade
version: '1.0'
main: net.mandomc.mandomcremade.MandoMCRemade
api-version: '1.20'
load: STARTUP
authors: [ AstuteFlamez ]
description: A core plugin for the minecraft server MandoMC.
softdepend: [MythicMobs,WorldGuard]
commands:
  warp:
    aliases: warps
  forcestartkoth:
  recipes:
  reload:
  pitch:
  yaw:
  vehicle:
  give:
  get:
  enchant:
    aliases: ce
